compatibility_date = "2021-11-08"
type = "webpack"
name = "hereditas-dev"
# Dev environment is deployed to a workers.dev domain
workers_dev = true
# Use CF_ACCOUNT_ID instead
#account_id = ""
# Use CF_ZONE_ID instead
#zone_id = ""
vars = {STORAGE_CONTAINER = "hereditas-dev", DOMAINS = "hereditas-dev.italypaleale.workers.dev"}
# These variables need to be set as secrets: PLAUSIBLE_ANALYTICS (except for dev), STORAGE_ACCOUNT

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
name = "hereditas-staging"
workers_dev = true
route = "staging.hereditas.app/*"
vars = {STORAGE_CONTAINER = "hereditas-staging", DOMAINS = "staging.hereditas.app"}

[env.production]
name = "hereditas"
workers_dev = true
route = "hereditas.app/*"
vars = {STORAGE_CONTAINER = "hereditas-prod", DOMAINS = "hereditas.app"}
